-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 03, 2023 at 01:19 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.0.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blogger`
--

-- --------------------------------------------------------

--
-- Table structure for table `blogs`
--

CREATE TABLE `blogs` (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `title` varchar(60) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `authorId` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `blogs`
--

INSERT INTO `blogs` (`id`, `title`, `description`, `createdAt`, `updatedAt`, `authorId`) VALUES
('0abc8be1-9487-4982-b732-4293e23776a9', 'Introduction to Computational Chemistry', 'Computational chemistry is a field of study that uses computer simulations to investigate the behavior of chemical systems. It involves the development and application of computational methods to solve chemical problems and to predict the properties of molecules and materials.\n\nComputational chemistry is used in a wide range of applications, including drug discovery, materials science, and environmental chemistry. It is also used to study the behavior of biological molecules, such as proteins and nucleic acids.\n\nOne of the key goals of computational chemistry is to understand the fundamental principles that govern chemical reactions and the behavior of molecules. This involves the development of computational models and algorithms that can accurately simulate chemical systems and predict their properties.\n\nComputational chemistry methods include molecular mechanics, molecular dynamics, and quantum chemistry. Molecular mechanics involves the use of classical mechanics to model the behavior of molecules, while molecular dynamics simulates the motion of atoms and molecules over time. Quantum chemistry involves the use of quantum mechanics to calculate the electronic structure of molecules and to predict their properties', '2023-04-28 04:48:02', '2023-04-28 04:48:02', '4269af63-06ba-48a8-9e50-c96743af6ad9'),
('0d77ad2e-7c0e-4521-a83f-b5f6bc24d3a2', 'Introduction to Computational Biology', 'Computational biology is a field of study that combines computer science, mathematics, and statistics with biological research to analyze and understand biological systems. It involves the development and application of computational methods to analyze large datasets generated from biological experiments and to model biological systems.\nThe field of computational biology encompasses a wide range of topics, including genomics, proteomics, transcriptomics, and metabolomics. It also includes the analysis of biological networks, such as metabolic pathways and gene regulatory networks, and the development of computational models to predict the behavior of biological systems.', '2023-04-28 04:30:11', '2023-04-28 04:30:11', '019cfe13-ee98-4071-82f8-4f90ca9ec54c'),
('1125dacb-adf1-4888-be55-1c3dee40d509', 'Introduction to Software Configuration Management', 'SCM is important because software development is an iterative and collaborative process that involves multiple developers and stakeholders. As a software project evolves, the code and related artifacts change, and managing these changes is essential to ensure that the software is stable, reliable, and maintainable.', '2023-04-26 03:40:28', '2023-04-26 03:40:28', '985f441e-de46-47aa-8f7d-74d28d9e11a2'),
('1ee6b779-e057-49d4-941f-4ea8141c331e', 'Introduction to Software Testing', 'Software testing is the process of evaluating a software system or application to ensure that it meets its requirements and works as intended. It involves executing software under controlled conditions and using a variety of techniques and tools to identify defects, errors, and other issues that could impact the quality, functionality, or performance of the software.', '2023-04-03 02:30:01', '2023-04-03 02:30:01', 'acd6f5ae-5c57-47aa-996d-5a877f9bf0fb'),
('207917fd-6edf-43ad-bfef-fbd958704e26', 'Introduction to Vue', 'Vue.js is an open-source JavaScript framework for building user interfaces and single-page applications. It was created by Evan You in 2014 and has since gained a large and active community of developers.\n\nSome of the key features of Vue.js include:\n\nReactive data binding: Vue.js provides a simple and efficient way to bind data to the DOM, allowing you to create dynamic and responsive user interfaces.\n\nComponent-based architecture: Vue.js allows you to break your application down into reusable components, making it easier to manage and scale your codebase.\n\nDirectives: Vue.js provides built-in directives that allow you to add dynamic behavior to your components, such as conditional rendering, event handling, and more.', '2023-05-02 10:59:58', '2023-05-03 09:41:53', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('2296f9d1-4546-4429-892e-f45f025d18ec', 'Introduction to Version Control', 'Version control involves tracking changes to software code, documentation, and other assets, and storing them in a centralized repository. This allows developers to work on different versions of the software in parallel and collaborate on changes.  Build management involves creating executable software from source code and other components. This typically involves compiling, linking, and packaging code into a distributable format.', '2023-04-27 05:57:31', '2023-04-27 06:03:55', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('2578fbf5-0a7d-46a9-aaf2-b5cf16083779', 'Introduction to Data Analytics', 'Data analytics refers to the process of examining large and complex data sets to identify patterns, trends, and insights that can help businesses make data-driven decisions. This involves collecting, cleaning, processing, and analyzing data using statistical and computational techniques to extract useful information.', '2023-04-26 03:05:46', '2023-04-26 03:05:46', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('3e32510b-86f4-4ebf-a22a-325b0d75f423', 'Introduction to Computer Science', 'Computer Science is a discipline that involves the study of computing systems, including their theory, design, development, and application. It involves the study of algorithms, programming languages, software engineering, database systems, computer architecture, artificial intelligence, and other related fields.\n\nComputer Science deals with the development of software and hardware systems that are used in various industries, including business, healthcare, entertainment, education, and government. The field has a broad range of applications, from designing and developing computer games to creating complex systems that analyze and process large amounts of data.', '2023-05-02 03:32:51', '2023-05-02 03:33:14', 'e7ea10bb-a191-4996-a881-562c2c780a90'),
('4587c921-c8ee-471d-aad0-af1e510a4d80', 'What is natural language processing', 'Natural language processing (NLP) is a subfield of artificial intelligence and computational linguistics that focuses on the interaction between computers and human language. The goal of NLP is to enable machines to understand, interpret, and generate natural language, the way humans do.\n\nNLP involves various tasks such as speech recognition, natural language understanding, language translation, sentiment analysis, and text generation. It uses techniques from computer science, linguistics, and machine learning to analyze and manipulate human language data.\n\nSome common applications of NLP include virtual assistants like Siri and Alexa, chatbots, automated language translation systems, spam filters, and sentiment analysis tools. NLP can also be used in industries such as healthcare, finance, and education to analyze and process large volumes of textual data.', '2023-05-02 04:09:32', '2023-05-02 04:09:32', 'a72d26e5-c36d-4351-993e-43491a3ad017'),
('476901fd-4bef-4f15-a65f-c04d601627fe', 'Introduction to Software Security', 'Software security is the practice of designing, implementing, and testing software systems and applications in a way that ensures they are protected from malicious attacks, vulnerabilities, and other security threats. It involves using a combination of software engineering, computer science, and security principles to build secure software that is resilient to attacks and breaches.', '2023-04-03 09:05:43', '2023-04-03 09:05:43', '5ca32cb8-5c35-4f77-96c3-517007593328'),
('4ba7502a-0635-44e0-8123-35e8fa236395', 'Introduction to Software Metrics', 'Software metrics are quantitative measures of software products, processes, and projects that help to assess their quality, performance, and efficiency. They provide objective data that can be used to evaluate the effectiveness of software development and maintenance activities, identify areas for improvement, and track progress towards project goals.', '2023-04-18 06:48:18', '2023-04-18 06:48:18', '76fcf668-2421-4ec6-9c33-b136d4d5213d'),
('5025af55-15c5-44f6-85d1-bd21e6f30cea', 'Introduction to Computer Engineering', 'Computer engineers work on various aspects of computer systems, including microprocessors, memory systems, input/output devices, networks, and software applications. They use their knowledge of digital circuits, computer architecture, programming languages, and algorithms to create efficient and reliable computer systems.', '2023-04-26 09:25:02', '2023-04-26 09:25:02', '0a9556be-3703-4ce6-835f-73754737642e'),
('51ddee41-44a7-4cc7-be19-89bcdbd58a06', 'Introduction to Software Engineering', 'The development phase involves writing the code and integrating the different components of the software system. Testing is a crucial part of the process, where the software is rigorously tested to ensure it meets the requirements and is free of errors and bugs.\n\nFinally, the software is deployed, and ongoing maintenance and updates are performed as needed to keep the system running smoothly.\n\nSoftware engineering is essential for creating reliable, scalable, and maintainable software systems. It requires a strong technical foundation in programming, algorithms, data structures, and system architecture, as well as skills in project management, communication, and collaboration.', '2023-05-02 03:36:08', '2023-05-02 03:36:08', 'e7ea10bb-a191-4996-a881-562c2c780a90'),
('5d03242c-55e7-4b6d-a7be-025358484bd6', 'Introduction to Software Design', 'Software design is the process of creating a plan or blueprint for a software system or application that meets the requirements of users, stakeholders, and customers. It involves translating the software requirements into a detailed design that specifies how the software will be structured, organized, and implemented.', '2023-04-05 06:59:56', '2023-04-05 06:59:56', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('62f0f530-d0e2-489c-9850-bf589d9c5e4c', 'Introduction to Computational Chemistry', 'Computational chemistry is a field of study that uses computer simulations to investigate the behavior of chemical systems. It involves the development and application of computational methods to solve chemical problems and to predict the properties of molecules and materials.\n\nComputational chemistry is used in a wide range of applications, including drug discovery, materials science, and environmental chemistry. It is also used to study the behavior of biological molecules, such as proteins and nucleic acids.\n\nOne of the key goals of computational chemistry is to understand the fundamental principles that govern chemical reactions and the behavior of molecules. This involves the development of computational models and algorithms that can accurately simulate chemical systems and predict their properties.', '2023-04-28 04:30:32', '2023-04-28 04:30:32', '019cfe13-ee98-4071-82f8-4f90ca9ec54c'),
('6bc6f020-afe4-44d7-bbeb-9adba3003cd3', 'Introduction to Blockchain', 'Blockchains can be used for a variety of applications beyond digital currencies, such as supply chain management, identity verification, and voting systems. One of the key benefits of blockchain technology is that it enables trust between parties without the need for a central authority or intermediary, such as a bank or government agency. This is because each transaction is validated and verified by a network of nodes, making it virtually impossible to tamper with the data.', '2023-04-28 04:28:20', '2023-04-28 04:28:20', '9a0dfb08-a302-4d63-b855-972661b503af'),
('74d21f82-4ddc-4e96-a5c2-ee95d3ca62f9', 'Introduction to Software Testing', 'Software testing is the process of evaluating a software system or application to ensure that it meets its requirements and works as intended. It involves executing software under controlled conditions and using a variety of techniques and tools to identify defects, errors, and other issues that could impact the quality, functionality, or performance of the software.', '2023-03-31 05:05:07', '2023-03-31 05:05:07', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('76193069-6f69-430a-9c0d-6d62a917a34f', 'Introduction to Software Testing', 'Software testing is the process of evaluating a software system or application to ensure that it meets its requirements and works as intended. It involves executing software under controlled conditions and using a variety of techniques and tools to identify defects, errors, and other issues that could impact the quality, functionality, or performance of the software.', '2023-04-03 02:29:55', '2023-04-03 02:29:55', 'acd6f5ae-5c57-47aa-996d-5a877f9bf0fb'),
('77ed5f59-b560-47b5-be4a-8d98fb52e0cc', 'Introduction to Business Intelligence and Data Analytics', 'Together, data analytics and business intelligence can help businesses improve their operations, optimize their processes, and make more informed decisions. They are essential tools for businesses in today\'s data-driven world, where the ability to make sense of large amounts of data can be a key competitive advantage.', '2023-04-26 04:25:26', '2023-04-26 14:09:16', 'a72d26e5-c36d-4351-993e-43491a3ad017'),
('7824457c-b0a1-4f23-807a-db8b49e85d8f', 'Introduction to Data Mining', 'Data mining techniques can be divided into several categories, including clustering, classification, regression, and association rule mining. Clustering involves grouping similar objects together based on their characteristics, while classification involves predicting which category an object belongs to based on its features. Regression is used to predict a numerical value based on a set of input variables, while association rule mining is used to identify relationships between variables in a dataset.', '2023-04-28 04:28:41', '2023-04-28 04:28:41', '9a0dfb08-a302-4d63-b855-972661b503af'),
('7f24c257-2619-4e1e-9527-4997fbf66575', 'Introduction to Software Metrics', 'Software metrics are quantitative measures of software products, processes, and projects that help to assess their quality, performance, and efficiency. They provide objective data that can be used to evaluate the effectiveness of software development and maintenance activities, identify areas for improvement, and track progress towards project goals.', '2023-03-31 05:04:45', '2023-03-31 05:04:45', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('82ebc699-9823-4a01-8720-79ba4a0882cc', 'Introduction to Information Technology', 'The primary goal of IT is to provide reliable and efficient access to information. This can include managing databases of customer information, creating and managing computer networks for businesses, developing and maintaining software applications, and ensuring the security and integrity of information systems.', '2023-04-26 04:32:05', '2023-04-26 04:32:05', 'c4264fcd-78d4-4a4c-bc5c-b1ca191e0517'),
('8cf904fd-dad6-40ab-b61f-6f86a4e2e286', 'Introduction to Software Configuration', 'Software configuration management (SCM) is a key part of software configuration. SCM is the process of identifying, organizing, and controlling changes to software systems and their components, and ensuring that all changes are tracked and documented. SCM helps ensure that software systems are developed and maintained in a controlled and organized manner, with a focus on quality, reliability, and consistency.', '2023-04-27 05:56:25', '2023-04-27 05:56:25', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('8d58cafe-c31a-4e2d-9ed5-80066762faea', 'Introduction to Combinatorial Optimization', 'There are several common techniques used in combinatorial optimization, including integer programming, dynamic programming, greedy algorithms, and metaheuristics. Integer programming involves solving optimization problems where some or all of the variables are constrained to be integer values. Dynamic programming involves breaking a problem down into smaller subproblems and solving each subproblem iteratively. Greedy algorithms involve making locally optimal choices at each step, with the hope of achieving a globally optimal solution. Metaheuristics, such as genetic algorithms and simulated annealing, are heuristic methods that use randomization to explore the solution space and find near-optimal solutions.', '2023-04-28 04:28:59', '2023-04-28 04:28:59', '9a0dfb08-a302-4d63-b855-972661b503af'),
('8ee60974-10eb-4c51-a9b6-aac9514e7b9e', 'Introduction to Artificial Intelligence', 'Artificial Intelligence (AI) refers to the development of computer systems and algorithms that can perform tasks that typically require human intelligence, such as learning, reasoning, problem-solving, and perception. AI technologies are designed to enable machines to perceive and respond to their environment, learn from experience, and make decisions or predictions based on data.', '2023-04-26 05:06:56', '2023-04-26 05:06:56', '76fcf668-2421-4ec6-9c33-b136d4d5213d'),
('91172860-3232-47c9-821c-1d994c7503fd', 'Introduction to kubernetes.', 'Kubernetes, also known as K8s, is an open-source container orchestration platform designed to automate deploying, scaling, and operating application containers. It was originally developed by Google and is now maintained by the Cloud Native Computing Foundation (CNCF)\nKubernetes allows you to manage containerized applications and services by providing a scalable, reliable, and highly available infrastructure. With Kubernetes, you can deploy and manage containerized applications and services across a cluster of servers, without worrying about the underlying infrastructure.\n\nKubernetes provides a declarative API that allows you to specify the desired state of your applications and services, and it takes care of the rest. It automatically handles tasks such as scaling, load balancing, self-healing, and rolling updates, making it easy to manage complex containerized applications.', '2023-05-03 04:02:33', '2023-05-03 09:56:19', 'a72d26e5-c36d-4351-993e-43491a3ad017'),
('93b114e9-3553-42cf-976c-cf4eb549e9c0', 'Introduction to use effect', 'In this example, the useEffect hook is used to fetch data from a server when the component is mounted. The empty array [] passed as the second argument means that the effect will only run once, when the component is mounted.\n\nIf you provide a value to the array, the effect will run again whenever the value changes. For example, if you pass [props.id] as the array, the effect will run again whenever the id prop changes.\n\nIn summary, useEffect is a powerful hook that allows you to perform side effects in functional components, making them more flexible and powerful than ever before.', '2023-05-02 08:07:42', '2023-05-02 08:07:52', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('9f9aa901-e50a-4b18-a74b-f7765659ff15', 'Introduction to Computer Communications', 'Communication is the exchange of information between two or more entities, which can be humans, machines, or a combination of both. Communications technology refers to the technologies and tools that are used to facilitate communication, such as telephones, email, instant messaging, video conferencing, and more. Communication technology has advanced rapidly in recent years, with the advent of new digital technologies and the internet. This has led to a wide range of new communication methods, such as social media, online collaboration tools, and virtual reality.', '2023-04-28 04:27:58', '2023-04-28 04:27:58', '9a0dfb08-a302-4d63-b855-972661b503af'),
('a241b18e-f5a3-418e-a5e3-eba592fea1f0', 'Introduction to Artificial Intelligence', 'Artificial Intelligence (AI) refers to the development of computer systems and algorithms that can perform tasks that typically require human intelligence, such as learning, reasoning, problem-solving, and perception. AI technologies are designed to enable machines to perceive and respond to their environment, learn from experience, and make decisions or predictions based on data.', '2023-04-18 06:48:16', '2023-04-18 06:48:16', '76fcf668-2421-4ec6-9c33-b136d4d5213d'),
('a334d4db-536a-49c0-8dc4-640ce4337c7b', 'Introduction to Robotics Development', 'The development of robotics is driven by advances in technology, such as sensors, actuators, control systems, and artificial intelligence. Today, robots are becoming increasingly sophisticated, with advanced capabilities such as autonomous navigation, decision-making, and learning.', '2023-04-26 03:14:38', '2023-04-26 14:57:33', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('ad4328c7-f9e5-496c-b492-3216a2893413', 'Introduction to Embedded Systems', 'Embedded systems are used in a wide range of applications, including consumer electronics, medical devices, automotive systems, industrial control systems, and aerospace systems. They typically have limited resources in terms of processing power, memory, and energy consumption, and must operate reliably in real-time environments.', '2023-04-28 04:29:46', '2023-04-28 04:29:46', '019cfe13-ee98-4071-82f8-4f90ca9ec54c'),
('b3dfe711-8a57-4800-a9d9-95f31c025526', 'What is HPC?', 'HPC systems also rely on specialized software tools and programming models that allow developers to take full advantage of the parallel processing capabilities of these systems. These tools include programming languages like MPI, OpenMP, and CUDA, which are designed to facilitate the development of parallel algorithms and applications.', '2023-04-26 04:18:49', '2023-04-26 04:18:49', 'a72d26e5-c36d-4351-993e-43491a3ad017'),
('b58c478d-0f1b-4de4-af9b-7c90230d0bfa', 'Introduction to Computational Biology', 'Computational biology is a field of study that combines computer science, mathematics, and statistics with biological research to analyze and understand biological systems. It involves the development and application of computational methods to analyze large datasets generated from biological experiments and to model biological systems.\n\nThe field of computational biology encompasses a wide range of topics, including genomics, proteomics, transcriptomics, and metabolomics. It also includes the analysis of biological networks, such as metabolic pathways and gene regulatory networks, and the development of computational models to predict the behavior of biological systems.\n\nOne of the key challenges in computational biology is the management and analysis of large datasets. Biological experiments can generate vast amounts of data, and computational methods are needed to extract meaningful information from this data. This requires the use of specialized algorithms and software tools that can handle large datasets and perform complex analyses.', '2023-04-28 04:48:22', '2023-04-28 04:48:22', '4269af63-06ba-48a8-9e50-c96743af6ad9'),
('c7204622-723b-48eb-b6c4-2dc1b54de713', 'Introduction to Data Analytics & Business Intelligence', 'Data analytics refers to the process of examining large and complex data sets to identify patterns, trends, and insights that can help businesses make data-driven decisions. This involves collecting, cleaning, processing, and analyzing data using statistical & computational techniques to extract useful information.\n\nBusiness intelligence, on the other hand, refers to the tools, technologies, and strategies that businesses use to collect, analyze, and visualize data to gain insights and make informed decisions. This can include dashboards, reports, data warehouses, and other tools that help businesses manage and use data effectively.', '2023-05-02 04:12:58', '2023-05-03 03:26:26', 'a72d26e5-c36d-4351-993e-43491a3ad017'),
('d7cd8fde-bcf3-4fb4-b148-146c264d90cd', 'Introduction to Software Design', 'Software design is the process of creating a plan or blueprint for a software system or application that meets the requirements of users, stakeholders, and customers. It involves translating the software requirements into a detailed design that specifies how the software will be structured, organized, and implemented.', '2023-04-05 06:59:19', '2023-04-05 06:59:19', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('d8d94b18-599b-4f1e-a708-a6ee7db7818f', 'Introduction to Information Security', 'Information security, also known as cybersecurity or IT security, is the practice of protecting computer systems, networks, and sensitive information from unauthorized access, use, disclosure, disruption, modification, or destruction. It involves using various measures and technologies to safeguard digital assets and prevent them from being compromised, stolen, or lost.', '2023-04-03 02:30:03', '2023-04-03 02:30:03', 'acd6f5ae-5c57-47aa-996d-5a877f9bf0fb'),
('dbfcb70e-f45c-4a49-b58a-2debdebeb3e3', 'Introduction to Information Security', 'Information security, also known as cybersecurity or IT security, is the practice of protecting computer systems, networks, and sensitive information from unauthorized access, use, disclosure, disruption, modification, or destruction. It involves using various measures and technologies to safeguard digital assets and prevent them from being compromised, stolen, or lost.', '2023-04-18 06:48:22', '2023-04-18 06:48:22', '76fcf668-2421-4ec6-9c33-b136d4d5213d'),
('e366821a-abab-4c79-8f6e-76bf03cb55c3', 'Introduction to Business Intelligence', 'Business intelligence, on the other hand, refers to the tools, technologies, and strategies that businesses use to collect, analyze, and visualize data to gain insights and make informed decisions. This can include dashboards, reports, data warehouses, and other tools that help businesses manage and use data effectively.', '2023-04-26 03:08:13', '2023-04-26 03:08:13', '2ed99fff-e742-4a26-b840-c2a7248f351a'),
('ea9347ab-fcd7-4c3a-af1c-c00722b8acd5', 'Introduction to High-Performance Computing', 'HPC systems typically consist of large clusters of interconnected computers or servers that work together to perform computational tasks in parallel. These systems can deliver processing speeds far beyond what is possible with a single computer, making them ideal for applications that require massive amounts of processing power, such as scientific simulations, weather forecasting, and drug discovery.', '2023-04-26 03:49:42', '2023-04-26 03:49:42', '985f441e-de46-47aa-8f7d-74d28d9e11a2'),
('ee5a5f83-c1d2-47f4-8540-3a4d2043eaa8', 'Introduction to Software Design', 'Software design is the process of creating a plan or blueprint for a software system or application that meets the requirements of users, stakeholders, and customers. It involves translating the software requirements into a detailed design that specifies how the software will be structured, organized, and implemented.', '2023-04-03 02:29:58', '2023-04-03 02:29:58', 'acd6f5ae-5c57-47aa-996d-5a877f9bf0fb');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blogs`
--
ALTER TABLE `blogs`
  ADD PRIMARY KEY (`id`),
  ADD KEY `authorId` (`authorId`);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `blogs`
--
ALTER TABLE `blogs`
  ADD CONSTRAINT `blogs_ibfk_1` FOREIGN KEY (`authorId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
